=== nehachoudhari/DigitalYearbook/WebContent/Student.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element type="xs:int" name="buckId"/>
              <xs:element type="xs:string" name="fname"/>
              <xs:element type="xs:string" name="lname"/>
              <xs:element type="xs:long" name="contactNumber"/>
              <xs:element type="xs:string" name="email"/>
              <xs:element type="xs:string" name="dob"/>
              <xs:element type="xs:string" name="gradYear"/>
              <xs:element type="xs:string" name="userName"/>
              <xs:element type="xs:string" name="password"/>
              <xs:element type="xs:short" name="deptId"/>
              <xs:element type="xs:string" name="job"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nehachoudhari/DigitalYearbook/WebContent/ModifyStudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Student Student.xsd">
<student>
  <buckId>2000001545</buckId>
  <fname>Nayan</fname>
  <lname>Khodke</lname>
  <contactNumber>6140000000</contactNumber>
  <email>khodke.2@osu.edu</email>
  <dob>12/25/1989</dob>
  <gradYear>7/22/2015 </gradYear>
  <userName>nayank</userName>
  <password>nayank</password>
  <deptId>1000</deptId>
  <job>-</job>
</student>
</students>

=== nehachoudhari/DigitalYearbook/DeleteStudent.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Student Student.xsd">
<student>
  <buckId>2000045699</buckId>
  <fname>Neha</fname>
  <lname>Choudhari</lname>
  <contactNumber>6145555474</contactNumber>
  <email>choudhari.4@osu.edu</email>
  <dob>08/23/1990</dob>>
  <gradYear> 7/22/2015 </gradYear>
  <userName>nehac</userName>
  <password>nehac</password>
  <deptId>1000</deptId>
  <job>Summer intern at Amazon</job>
</student>
</students>

=== nehachoudhari/DigitalYearbook/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Student Student.xsd">
<student>
  <buckId>2000001545</buckId>
  <fname>Nayan</fname>
  <lname>Khodke</lname>
  <contactNumber>6145555454</contactNumber>
  <email>khodke.1@osu.edu</email>
  <dob>12/25/1989</dob>
  <gradYear>7/22/2015 </gradYear>
  <userName>nayank</userName>
  <password>nayank</password>
  <deptId>1000</deptId>
  <job>Summer intern at JP Morgan Chase</job>
</student>
<student>
  <buckId>2000045699</buckId>
  <fname>Neha</fname>
  <lname>Choudhari</lname>
  <contactNumber>6145555474</contactNumber>
  <email>choudhari.4@osu.edu</email>
  <dob>08/23/1990</dob>>
  <gradYear> 7/22/2015 </gradYear>
  <userName>nehac</userName>
  <password>nehac</password>
  <deptId>1000</deptId>
  <job>Summer intern at Amazon</job>
</student>
<student>
  <buckId>2000045779</buckId>
  <fname>Virinchi</fname>
  <lname>Jalaparti</lname>
  <contactNumber>6145552474</contactNumber>
  <email>jalaparti.1@osu.edu</email>
  <dob>11/23/1989</dob>>
  <gradYear>7/22/2015 </gradYear>
  <userName>virinchij</userName>
  <password>virinchij</password>
  <deptId>1000</deptId>
  <job>Research work in Summer</job>
</student>
<student>
  <buckId>2000003454</buckId>
  <fname>Abhang</fname>
  <lname>Sonawane</lname>
  <contactNumber>123234543</contactNumber>
  <email>a.b@osu.edu</email>
  <dob>11/23/1989</dob>>
  <gradYear>7/22/2015 </gradYear>
  <userName>abhangs</userName>
  <password>abhangs</password>
  <deptId>1000</deptId>
  <job>Nationwide</job>
</student>
</students>
